#!/usr/bin/env bash

if [ -z "$DEV_ENV" ]; then
	echo "DEV_ENV has not been set"
	exit 1
fi

if [ -z "$XDG_CONFIG_HOME" ]; then
	echo "setting config to ~/.config"
	XDG_CONFIG_HOME=$HOME/.config
fi

dry_run=0

for arg in "$@"
do
	case "$arg" in
		--dry)	echo "performing dry run"
				dry_run=1
				;;
		esac				
done

log() {
	if [ $dry_run -eq 1 ]; then
		echo "[DRY_RUN]: $1"
	else
		echo "$1"
	fi
}

copy_folder_env() {
	log "copying files from $1"
	pushd $1 &> /dev/null 
	
	{
		configs=`find . -mindepth 1 -maxdepth 1 -type d`
		for c in $configs; do
			directory=${2%/}/${c#./}
			log "removing: $directory"
			if [ $dry_run -eq 0 ]; then
				rm -rf $directory
			fi

			log "copying: $c to $2"
			if [ $dry_run -eq 0 ]; then
				cp -r $c $2
			fi
		done
	}

	popd &> /dev/null
}

copy_file_env() {
	log "removing $2"
	if [ $dry_run -eq 0 ]; then
		rm $2
	fi

	log "copying: $1 to $2"
	if [ $dry_run -eq 0 ]; then
		cp $1 $2
	fi
}

copy_folder_env $DEV_ENV/env/.config $XDG_CONFIG_HOME

copy_file_env $DEV_ENV/env/kdeglobals $XDG_CONFIG_HOME/kdeglobals
